### PR TITLE
Add thread safety to Observable.value

### PR DESCRIPTION
**Pull request by 4brunu**
Solves https://github.com/roberthein/Observable/issues/11

### CODE REVIEW

**Comment by roberthein** [comment]
This looks pretty smart. 😃 But Im AFK now, will look at it tomorrow.

**Comment by 4brunu** [comment]
No problem! 🙂 Thanks for all the feedback and approving the other PR today 👍 😄

**Comment by 4brunu** [comment]
Just made some additional changes, UniqueID and Observers should also be thread safe

**Comment by roberthein** [comment]
Very nice! I was just looking at a good way to test this stuff.. let's get this merged ;)

**Comment by 4brunu** [comment]
I was thinking that this project could have a test suite.
I could create some tests, but since this don't have an Xcode project, I'm not sure where to create the test target and start adding the tests...
What do you think?

**Comment by roberthein** [comment]
Great idea again. There could just be a Xcode project living in the root-folder.

**Pull request merged**
