### PR TITLE
Firing first event using thread

### PR DESCRIPTION
**Pull request by Edudjr**
This PR fixes the issue #32 where the first time we call the observer, right after subscribing, we where not using the given queue from the parameter.

### CODE REVIEW

**Comment by 4brunu** [comment]
@Edudjr could you please fix the conflicts? 🙂

**Comment by Edudjr** [comment]
@4brunu sure! I didn't have the latest merge 😅

**Comment by Edudjr** [comment]
I also took the liberty of creating a test target and test scenarios to be sure it would work with these changes, it can be found here:
https://github.com/roberthein/Observable/compare/master...Edudjr:bugfix/unit-tests?expand=1
I'm not sure what are the plans about unit testing this library, that's why I didn't open the PR :)

**Comment by 4brunu** [comment]
Let see what @roberthein thinks on that 🙂

**Comment by roberthein** [comment]
Yes @Edudjr! Create the PR! Looks good! Would be nice to make it part of this update. I'll merge it ASAP and push the new version. 🙏

**Comment by roberthein** [comment]
Works great @Edudjr! Thank you very much!

**Comment by Edudjr** [comment]
@roberthein thanks for the quick update! Glad to help :)

**Pull request merged**
