### PR TITLE
Replaces Lock with DispatchQueues to avoid deadlock

### PR DESCRIPTION
**Pull request by lm2s**
Replaces Lock with DispatchQueues to avoid deadlock when updating an Observable value from within its Observation.

Added a read/write queue for set/get the value and added another queue to decoupled the changes broadcasting to observers from the read/write.

### CODE REVIEW

**Comment by AlexandrGraschenkov** [comment]
So we need one tread for one observable? 100 observables = 100 threads? If we don't have problems with deadlock, better do not switch threads. When we switch tread a lot of magic goes there. As minimum context switch.

If you have deadlock problem somewere, just set observe queue.

**Comment by lm2s** [comment]
@AlexandrGraschenkov A DispatchQueue is not a Thread, it's a queue. The system manages a pool of threads which are used to dispatch work from each queue. So 100 queues might just be 10 threads or however the systems decides it.

Still you bring a good point about having a DispatchQueue per observable. This might not be the most efficient way of doing this, but I disagree that ignoring this deadlock problem is the way to go.

**Comment by AlexandrGraschenkov** [comment]
@lm2s it's not ignoring deadlock problem. If you have it, just use external thread. If switch thread don't cost anything, this solution will be great.

**Comment by AlexandrGraschenkov** [comment]
If it's not obvious for user, we can add additional method `updateSafe(value: T)`. And change value async in private queue.

**Comment by lm2s** [comment]
@AlexandrGraschenkov I did some tests and came to the same conclusion as you, there's some overhead. Which I expected but not so much as I found, especially in the creation of each Observable.

The `readWriteQueue` is unnecessary if we use the Mutex and having a static DispatchQueue (instead of 1 per Observable) to dispatch the observers `forEach` would vastly reduce the overhead and fix this deadlock issue, which I still think should not happen without requiring assistance from the developer. But I have no time to do performance tests regarding the possible thread context switching and as such I agree that we should go back to the Mutex and, if required, use a different DispatchQueue on the observe method.

**Pull request merged**
