### PR TITLE
Property wrapper

### PR DESCRIPTION
**Pull request by mzahidimran**
This pull request adds propertyWrappers so one can have already mapped models properties to obserable just by adding `@Observable`

### CODE REVIEW

**Comment by bfrolicher** [comment]
@roberthein will this pull request be integrated?

**Comment by 4brunu** [comment]
This is a nice addition, but I think this will make the library only work on iOS 13...
Because property wrappers are only available in iOS 13 and above.
Is there any way to have this and still be backwards compatible?

**Comment by mzahidimran** [comment]
Property wrappers are backward compatible I believe. As its offered in Swift5 nothing related to iOS SDK. I'm away from my mac will let you know surely. I've used this in my demo code [https://github.com/mzahidimran/MVVMC](https://github.com/mzahidimran/MVVMC) which is I guess iOS 12 compatible will let you know for sure

**Comment by mzahidimran** [comment]
> This is a nice addition, but I think this will make the library only work on iOS 13...
> Because property wrappers are only available in iOS 13 and above.
> Is there any way to have this and still be backwards compatible?

Implemented in Example project, you may verify by building example project :)

**Comment by 4brunu** [comment]
@mzahidimran thanks for the quick response.
I read more about it and you are right!
I also tested your project on iOS 11 and it's working 👍

**Comment by roberthein** [comment]
Thank you @mzahidimran for this cool add-on. 👌🙏

**Pull request merged**
