### PR TITLE
Migrate to Observable and MutableObservable

### PR DESCRIPTION
**Pull request by 4brunu**
As discussed in https://github.com/roberthein/Observable/issues/24, this PR tries to fix the issue.
@roberthein What do you think about this? I would like to know your opinion on this.
Thanks

### CODE REVIEW

**Comment by roberthein** [comment]
I think I needed some incubation time to adjust to this, but I do see the advantage now.. I'll take this up in the next release later today. Thank you for your effort! 👌

**Comment by 4brunu** [comment]
No problem, thanks for taking a look at this 👍

**Comment by roberthein** [comment]
That was fast @4brunu 😂

**Comment by 4brunu** [comment]
I subscribed to the other PR 😄

**Comment by 4brunu** [comment]
Thanks for merging this 👍 
Maybe before next release, https://github.com/roberthein/Observable/issues/32 should be fixed, what do you think?

**Comment by roberthein** [comment]
I believe @Edudjr is working on a PR for this..

**Comment by 4brunu** [comment]
I think so, I was just saying that maybe it's worth waiting to that PR before the next release. 
Or then another release can be created 🙂

**Comment by roberthein** [comment]
Yes, good idea, let's wait for that.

**Pull request merged**
